language: java
os: linux
dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-wire.git
- cd vlingo-wire && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-cluster.git
- cd vlingo-cluster && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-symbio.git
- cd vlingo-symbio && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-lattice.git
- cd vlingo-lattice && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
jdk: openjdk8
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: vaughnvernon
  on:
    branch: master
  key:
    secure: iyHRwuxdPG7asRlnkEnrGxb8+ZOYZV9Vz2QCqKOlHk4QR48nDvoD3msX0AGXYOAbXCuSdweADP7NIe0LhqZ9D6JLvmdnJWXRjAvfook1Zq4J/7j4hkthL63g2qZ8VRIEi6A8XJRHC1SM+OqFCrsPJJjr23+OB5YTqxdSkHcbHUupPwMxI1U6ScL+3KORi1Qk0bmTllC9VL5hL8U3DyujHyyLFow9zdS29mO9S74CC59OQidTRPDBVWkZqOKpgfQcK4AHAnFffxZFJLxWP+YKst1u66DNfUUxx26Qa0XfmHwo16bbZqGMLmd9WD245HDZ8vTKwm14HVf9ZfIVxPYbZTNW/egxYOCjJW1U4ofOS5/TpAoHpzko+Bb4rvIEzSeyooVovv54pa4/9Kh7vuAsk3tgu6TMJhTwj5X0bAyKyhgDsZJNGRoSKj64bqSPTvsZTFIZ2Vg+OXKGmDLh7e9UnElAq/vnESs2c1suTosVB1QHCGwiKpMZIh9ej+4HTc9UTga6jvJxGd6lLTa9Te0c7+wZEJg+SV1wnYfXuMRG6Lxaf7IhzhFUIp4n3IMVakvHlPCoVzIq/CHknqAr0310gsYTGAVteCLzWokvx9PnCBEBkmDhVPIvecpKuY2kLkX9eK0L8OL9529GNIvt/jvVgDtjpLF/tS+fdxKSyUN2o3o=
  passphrase:
    secure: jno/hK+LJjINavDAPfUnNcBtXYqih1HETU7TcaTJbo3zePzfXLJSx2YdVyXFRcf3yEnTIv2Ib7yyry3KSYBiMcZPFMOinP0jwERH+ylIfa0IsiEASwhytG1uTBiURhqQuLeST4FsL/sO/XEfGkfY585RzcnYEKyWpb59b69sqgs91T9uGZBDjnq+a1W+5qei02A63K+vK0vRzAFGhutLcSzIwgGnwjEDbXIXJnG9W9iuK9CGoGqIz50TCwWDek+gSNdTL5H/rjZqVPuIaetoqSd0kh3PFdkjSiHxQJ/mmNZWAM1o7H1TA+efywvCmKgan344d+LyKMkR3kVfb2yl7Rb0a2Bqd3g4+16omf0P53q1fZgPO+oRcXb6kC80jqKNGJX67sS8C1w1HpcVZp/tNuVmUzw/9/SmQ1G76IrWA3XTdmlgqvZUu+gH14dN24ofoBu6vWAmt2bKN3nBkp4Xck+eDnoe2zs6yaE0Q2WpM1ULLnpgzvxSlyGdJf2lf6w1DRoaoFF7B3cXqXMNF4X8N+rmJw8WcG4y7nndtuuIGxoCE+/aQWZCRB9Z7sByv2plaDuaXt/mgnA8lHCR/CZgAqgYRHHYEA9T8Jk+Fp20bC9kKd6j9Oa8kDaIpPQwy/I5jj536g/msctJykuFBh2nlJdCNFyVgX/xegDE2r0IC/g=
notifications:
  slack:
    secure: AgEmeaQl5W+pb11ThGexSGdjQGHnkpOmRiQRBQbpcbG+B9JrItWirboKbLN4MlLMFz+sAX3IBI9LY09IcWT/ycmn4rXDIdfdfzH3edS5PXUkUZ3Ew8IaQ641OqZqhg/CbvacD/Pyv2gGCvF5UfRfKVrsNa7rQkGefP1mkQ4Z71bVxe+sokVDZYyInwVD5VuxIDCsmuM6AsbpQo8vGa6LvMlnqNhC5AYuOwWRntqrb6ncNYwuPUw5zT5cG43qr3iIlBP9uOr7+wgg1cAysMs3kd2uyq5g0hKvKY/HqW++BO7qWNLwnBdTcU0ibbr17znXfbgSfhG0shHWrzVE81hkAMpVD5uxWA1O6+VFnXvhicGQyZPR9zD4tyO1cge9KulU3xW2ZSO+vWJ0LahaszngFRaMETl7JtVddYJ8uT0Bsq8YyEaP9yOrXggt+MTp2XxtmTFCFdLs2T2BG7Ujz6+DsxbghYdTYN6lmhyZZSzPKqz/5/gpyo6HbP0byc4LQUM59RsG+sLckh9/FQHBAPwKgplcwiszMik/a2KnAlBrTasoXFWkfqeXrQJnZuDZp+JMs5Z9UMZeaGKrn+si8olBcMYEKOeoGsy2UrbSOMvwlew94C+6gSLfKOKhDswsCuMEj6B4ZAl4L1T3cvRRrVyViilTKbzhs9b2QBNXBBktJ2k=
